version: '3'
services:
    app:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - shared-database
        depends_on:
            #- mysql
            - redis

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        profiles:
            - database

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            REDIS_HOSTS: redis
            REDIS_HOST: redis
            REDIS_PORT: redis:6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            HTTP_USER: root
            HTTP_PASSWORD: root
            URL_PREFIX: /redis
        ports:
            - '${FORWARD_REDIS_COMMANDER_PORT:-8081}:8081'
        networks:
            - sail

    adminer:
        build:
            context: ./docker/adminer
            dockerfile: Dockerfile
        image: adminer
        ports:
            - "${FORWARD_ADMINER_PORT:-8080}:8080"
        networks:
            - sail
        depends_on:
            - mysql
        volumes:
            - 'sail-adminer:/var/lib/adminer'
        profiles:
            - database

networks:
    sail:
        driver: bridge
    shared-database:
        external: true

volumes:
    dbdata:
    sail-redis:
        driver: local
    sail-adminer:
        driver: local